let express = require("express");
let app = express();    
     
app.listen(8000, function(){
    console.log("Servidor iniciado...");
})

app.use(express.static('html_06'));


app.get("/servicios/autocompletar", function(request, response){
    console.log("=================================="); 
    let campo = request.query.campo;
    let valor = request.query.valor;

    if(campo=="ciudad"){
    let respuesta = campo+"|";
        for(let a=0;a<ciudades.length;a++){
            if(ciudades[a].toUpperCase().startsWith(valor.toUpperCase())){
                respuesta = respuesta+"|"+ciudades[a];
            }
        }
    }
    response.send(respuesta);
});



let ciudades = [];  

	       ciudades.push("Santa Pola 33.372 Alicante Comunidad Valenciana ");
	 	   ciudades.push("Madrid 3.128.600 Madrid  Comunidad de Madrid ");
		   ciudades.push("Barcelona 1.605.602 Barcelona  Cataluña   ");
		   ciudades.push("Valencia 1.009.670 Valencia  Comunidad Valenciana ");
		   ciudades.push("Sevilla 704.414 Sevilla  Andalucía ");
		   ciudades.push("Zaragoza 667.034 Zaragoza  Aragón  ");
		   ciudades.push("Málaga 573.000 Málaga  Andalucía ");
		   ciudades.push("Murcia 416.996 Murcia  Región de Murcia ");
		   ciudades.push("Las Palmas de G. C. 377.056 Las Palmas  Canarias ");
		   ciudades.push("Palma de Mallorca 375.048 Islas Baleares  Islas Baleares ");
		   ciudades.push("Bilbao 354.145 Vizcaya  País Vasco ");
		   ciudades.push("Córdoba 322.867 Córdoba  Andalucía ");
		   ciudades.push("Alicante 322.431 Alicante  Comunidad Valenciana ");
		   ciudades.push("Valladolid 319.943 Valladolid  Castilla y León  ");
		   ciudades.push("Vigo 293.255 Pontevedra  Galicia ");
		   ciudades.push("Gijón 274.472 Asturias  Asturias ");
		   ciudades.push("Hospitalet de Llobregat 248.150 Barcelona  Cataluña  ");
		   ciudades.push("La Coruña 243.320 La Coruña  Galicia ");
		   ciudades.push("Granada 237.929 Granada  Andalucía ");
		   ciudades.push("Vitoria 230.585 Álava  País Vasco ");
		   ciudades.push("S. C. de Tenerife 223.148 S. C. de Tenerife  Canarias ");
		   ciudades.push("Badalona 221.520 Barcelona  Cataluña  ");
		   ciudades.push("Elche 219.032 Alicante  Comunidad Valenciana ");
		   ciudades.push("Oviedo 214.883 Asturias  Asturias ");
		   ciudades.push("Móstoles 212.301 Madrid  Comunidad de Madrid ");
		   ciudades.push("Cartagena 211.329 Murcia  Región de Murcia ");
		   ciudades.push("Alcalá de Henares 204.000 Madrid  Comunidad de Madrid ");
		   ciudades.push("Tarrasa 201.442 Barcelona  Cataluña  ");
		   ciudades.push("Pamplona 200.569 Navarra  Navarra ");
		   ciudades.push("Sabadell 200.545 Barcelona  Cataluña  ");
		   ciudades.push("Jerez de la Frontera 199.544 Cádiz  Andalucía ");
		   ciudades.push("Fuenlabrada 195.131 Madrid  Comunidad de Madrid ");
		   ciudades.push("Almería 185.309 Almería  Andalucía ");
		   ciudades.push("San Sebastián 183.308 Guipuzcoa  País Vasco ");
		   ciudades.push("Santander 182.926 Cantabria  Cantabria ");
		   ciudades.push("Leganés 182.471 Madrid  Comunidad de Madrid ");
		   ciudades.push("Burgos 173.676 Burgos  Castilla y León  ");
		   ciudades.push("Castellón 172.110 Castellón  Comunidad Valenciana ");
		   ciudades.push("Alcorcón 162.524 Madrid  Comunidad de Madrid ");
		   ciudades.push("Albacete 161.508 Albacete  Castilla-La Mancha ");
		   ciudades.push("Salamanca 159.754 Salamanca  Castilla y León  ");
		   ciudades.push("Getafe 156.320 Madrid  Comunidad de Madrid ");
		   ciudades.push("Logroño 147.182 La Rioja  La Rioja ");
		   ciudades.push("Huelva 145.763 Huelva  Andalucía ");
		   ciudades.push("Badajoz 143.748 Badajoz  Extremadura ");
		   ciudades.push("San Cristóbal de la Laguna 142.161 S. C. de Tenerife  Canarias ");
		   ciudades.push("León 136.985 León  Castilla y León  ");
		   ciudades.push("Lérida 132.000 Lérida  Cataluña  ");
		   ciudades.push("Tarragona 131.158 Tarragona  Cataluña  ");
		   ciudades.push("Cádiz 130.561 Cádiz  Andalucía ");
		   ciudades.push("Marbella 125.519 Málaga  Andalucía ");
		   ciudades.push("Algeciras 123.714 Cádiz  Andalucía ");
		   ciudades.push("Santa Coloma de Gramanet 119.056 Barcelona  Cataluña  ");
		   ciudades.push("Mataró 118.748 Barcelona  Cataluña   ");
		   ciudades.push("Jaén 116.769 Jaén  Andalucía ");
		   ciudades.push("Dos Hermanas 114.672 Sevilla  Andalucía ");
		   ciudades.push("Torrejón de Ardoz 109.483 Madrid  Comunidad de Madrid ");
		   ciudades.push("Orense 108.137 Orense  Galicia ");
		   ciudades.push("Alcobendas 107.098 Madrid  Comunidad de Madrid ");
		   ciudades.push("Reus 104.835 Tarragona  Cataluña  ");
		   ciudades.push("Parla 102.458 Madrid  Comunidad de Madrid ");
		   ciudades.push("Cáceres 100.281 Cáceres  Extremadura ");
		   ciudades.push("Torrevieja 100.125 Alicante  Comunidad Valenciana ");
		   ciudades.push("Baracaldo 95.675 Vizcaya  País Vasco ");
		   ciudades.push("San Fernando 93.544 Cádiz  Andalucía ");
		   ciudades.push("Santiago de Compostela 92.919 La Coruña  Galicia ");
		   ciudades.push("Lugo 92.271 Lugo  Galicia ");
		   ciudades.push("Coslada 91.906 Madrid  Comunidad de Madrid ");
		   ciudades.push("Lorca 89.936 Murcia  Región de Murcia ");
		   ciudades.push("Gerona 89.890 Gerona  Cataluña  ");
		   ciudades.push("Cornellá de Llobregat 84.131 Barcelona  Cataluña ");
		   ciudades.push("Talavera de la Reina 83.793 Toledo  Castilla-La Mancha ");
		   ciudades.push("Avilés 83.538 Asturias  Asturias ");
		   ciudades.push("El Puerto de Santa María 83.101 Cádiz  Andalucía ");
		   ciudades.push("Guecho 82.327 Vizcaya  País Vasco ");
		   ciudades.push("Palencia 82.263 Palencia  Castilla y León  ");
		   ciudades.push("Sant Boi de Llobregat 81.368 Barcelona  Cataluña  ");
		   ciudades.push("Pontevedra 80.191 Pontevedra  Galicia ");
		   ciudades.push("Pozuelo de Alarcón 79.581 Madrid  Comunidad de Madrid ");
		   ciudades.push("Guadalajara 78.115 Guadalajara  Castilla-La Mancha ");
		   ciudades.push("Orihuela 77.979 Alicante  Comunidad Valenciana ");
		   ciudades.push("Toledo 77.601 Toledo  Castilla-La Mancha ");
		   ciudades.push("Ferrol 77.155 La Coruña  Galicia ");
		   ciudades.push("Las Rozas 76.246 Madrid  Comunidad de Madrid ");
		   ciudades.push("El Ejido 75.969 Almería  Andalucía ");
		   ciudades.push("Ceuta 75.861 Ceuta  Ceuta ");
		   ciudades.push("Chiclana de la F. 75.338 Cádiz  Andalucía ");
		   ciudades.push("Gandía 74.827 Valencia  Comunidad Valenciana ");
		   ciudades.push("Torrente 74.616 Valencia  Comunidad Valenciana ");
		   ciudades.push("San Cugat del Vallés 73.774 Barcelona  Cataluña   ");
		   ciudades.push("Roquetas de Mar 71.740 Almería  Andalucía ");
		   ciudades.push("Manresa 70.343 Barcelona  Cataluña   ");
		   ciudades.push("Ciudad Real 70.124 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Rubí 70.006 Barcelona  Cataluña  ");
		   ciudades.push("Arona 69.100 S. C. de Tenerife  Canarias ");
		   ciudades.push("Vélez-Málaga 67.697 Málaga  Andalucía ");
		   ciudades.push("Benidorm 67.627 Alicante  Comunidad Valenciana ");
		   ciudades.push("S. Sebastián de los R. 67.351 Madrid  Comunidad de Madrid ");
		   ciudades.push("Melilla 66.871 Melilla  Melilla ");
		   ciudades.push("Ponferrada 66.656 León  Castilla y León  ");
		   ciudades.push("Zamora 66.123 Zamora  Castilla y León  ");
		   ciudades.push("Alcalá de Guadaíra 64.990 Sevilla  Andalucía ");
		   ciudades.push("Fuengirola 63.899 Málaga  Andalucía ");
		   ciudades.push("Sanlúcar de Barrameda 63.509 Cádiz  Andalucía ");
		   ciudades.push("El Prat de Llobregat 63.190 Barcelona  Cataluña  ");
		   ciudades.push("La Línea de la C. 63.026 Cádiz  Andalucía ");
		   ciudades.push("Vilanova i la Geltrú 62.826 Barcelona  Cataluña  ");
		   ciudades.push("Sagunto 62.702 Valencia  Comunidad Valenciana ");
		   ciudades.push("Majadahonda 62.270 Madrid  Comunidad de Madrid ");
		   ciudades.push("Molina de Segura 61.959 Murcia  Región de Murcia ");
		   ciudades.push("Linares 61.452 Jaén  Andalucía ");
		   ciudades.push("Mijas 61.147 Málaga  Andalucía ");
		   ciudades.push("Viladecans 61.043 Barcelona  Cataluña  ");
		   ciudades.push("Alcoy 60.590 Alicante  Comunidad Valenciana ");
		   ciudades.push("Irún 60.261 Guipuzcoa  País Vasco ");
		   ciudades.push("Granollers 58.940 Barcelona  Cataluña  ");
		   ciudades.push("Torremolinos 58.683 Málaga  Andalucía ");
		   ciudades.push("Estepona 58.603 Málaga  Andalucía ");
		   ciudades.push("Cerdañola del Vallés 57.959 Barcelona  Cataluña  ");
		   ciudades.push("Motril 57.895 Granada  Andalucía ");
		   ciudades.push("Collado Villalba 57.889 Madrid  Comunidad de Madrid ");
		   ciudades.push("Paterna 57.343 Valencia  Comunidad Valenciana ");
		   ciudades.push("Castelldefels 56.718 Barcelona  Cataluña  ");
		   ciudades.push("Torrelavega 56.407 Cantabria  Cantabria ");
		   ciudades.push("Segovia 55.476 Segovia  Castilla y León  ");
		   ciudades.push("Elda 55.138 Alicante  Comunidad Valenciana ");
		   ciudades.push("Mérida 53.915 Badajoz  Extremadura ");
		   ciudades.push("Rivas-Vaciamadrid 53.459 Madrid  Comunidad de Madrid ");
		   ciudades.push("Ávila 53.272 Ávila  Castilla y León  ");
		   ciudades.push("Aranjuez 52.875 Madrid  Comunidad de Madrid ");
		   ciudades.push("Mollet del Vallés 51.713 Barcelona  Cataluña  ");
		   ciudades.push("Cuenca 51.205 Cuenca  Castilla-La Mancha ");
		   ciudades.push("Puertollano 50.470 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Benalmádena 50.298 Málaga  Andalucía ");
		   ciudades.push("Siero 49.376 Asturias  Asturias ");
		   ciudades.push("Huesca 49.312 Huesca  Aragón  ");
		   ciudades.push("Portugalete 49.118 Vizcaya  País Vasco ");
		   ciudades.push("Valdemoro 48.517 Madrid  Comunidad de Madrid ");
		   ciudades.push("Utrera 48.222 Sevilla  Andalucía ");
		   ciudades.push("Villarreal 48.055 Castellón  Comunidad Valenciana ");
		   ciudades.push("Santurce 47.155 Vizcaya  País Vasco ");
		   ciudades.push("Esplugues de Llobregat 46.550 Barcelona  Cataluña  ");
		   ciudades.push("Langreo 46.076 Asturias  Asturias ");
		   ciudades.push("Mieres 45.645 Asturias  Asturias ");
		   ciudades.push("Arganda del Rey 45.085 Madrid  Comunidad de Madrid ");
		   ciudades.push("Basauri 45.085 Vizcaya  País Vasco ");
		   ciudades.push("Gavá 44.531 Barcelona  Cataluña  ");
		   ciudades.push("Antequera 44.032 Málaga  Andalucía ");
		   ciudades.push("Calviá 43.499 Islas Baleares  Islas Baleares ");
		   ciudades.push("Mislata 43.363 Valencia  Comunidad Valenciana ");
		   ciudades.push("Ibiza 42.884 Islas Baleares  Islas Baleares ");
		   ciudades.push("Boadilla del Monte 42.598 Madrid  Comunidad de Madrid ");
		   ciudades.push("Sant Feliu de Llobregat 42.267 Barcelona  Cataluña  ");
		   ciudades.push("Plasencia 42.170 Cáceres  Extremadura ");
		   ciudades.push("Tres Cantos 41.800 Madrid  Comunidad de Madrid ");
		   ciudades.push("Colmenar Viejo 40.706 Madrid  Comunidad de Madrid ");
		   ciudades.push("La Orotava 40.644 S. C. de Tenerife  Canarias ");
		   ciudades.push("Lucena 40.143 Córdoba  Andalucía ");
		   ciudades.push("San Fernando de Henares 40.048 Madrid  Comunidad de Madrid ");
		   ciudades.push("Figueras 39.641 Gerona  Cataluña  ");
		   ciudades.push("Pinto 39.432 Madrid  Comunidad de Madrid ");
		   ciudades.push("Écija 39.295 Sevilla  Andalucía ");
		   ciudades.push("Mairena del Aljarafe 39.065 Sevilla  Andalucía ");
		   ciudades.push("Andújar 38.662 Jaén  Andalucía ");
		   ciudades.push("Alcantarilla 38.584 Murcia  Región de Murcia ");
		   ciudades.push("Puerto Real 38.354 Cádiz  Andalucía ");
		   ciudades.push("Miranda de Ebro 38.276 Burgos  Castilla y León  ");
		   ciudades.push("Blanes 38.205 Gerona  Cataluña  ");
		   ciudades.push("Soria 38.004 Soria  Castilla y León  ");
		   ciudades.push("Igualada 38.000 Barcelona  Cataluña  ");
		   ciudades.push("Vic 37.825 Barcelona  Cataluña  ");
		   ciudades.push("Rentería 37.874 Guipuzcoa  País Vasco ");
		   ciudades.push("Manacor 37.165 Islas Baleares  Islas Baleares ");
		   ciudades.push("Vilafranca del Penedés 37.063 Barcelona  Cataluña  ");
		   ciudades.push("Adeje 36.764 S. C. de Tenerife  Canarias ");
		   ciudades.push("Los Realejos 36.746 S. C. de Tenerife  Canarias ");
		   ciudades.push("Úbeda 36.342 Jaén  Andalucía ");
		   ciudades.push("Villagarcía de Arosa 35.954 Pontevedra  Galicia ");
		   ciudades.push("Antequera 35.836 Málaga  Andalucía ");
		   ciudades.push("Tomelloso 35.534 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Ripollet 35.427 Barcelona  Cataluña  ");
		   ciudades.push("Los Palacios y Villafranca 35.225 Sevilla  Andalucía ");
		   ciudades.push("Narón 35.083 La Coruña  Galicia ");
		   ciudades.push("Cieza 34.735 Murcia  Región de Murcia ");
		   ciudades.push("Yecla 34.311 Murcia  Región de Murcia ");
		   ciudades.push("Tortosa 34.266 Tarragona  Cataluña  ");
		   ciudades.push("Don Benito 34.260 Badajoz  Extremadura ");
		   ciudades.push("Teruel 34.240 Teruel  Aragón  ");
		   ciudades.push("Granadilla de Abona 34.595 S. C. de Tenerife  Canarias ");
		   ciudades.push("Rincón de la Victoria 33.817 Málaga  Andalucía ");
		   ciudades.push("La Rinconada 33.370 Sevilla  Andalucía ");
		   ciudades.push("Sant Adrià del Besòs 32.585 Barcelona  Cataluña  ");
		   ciudades.push("Tudela 32.802 Navarra  Navarra ");
		   ciudades.push("Moncada i Reixac 32.153 Barcelona  Cataluña  ");
		   ciudades.push("Almendralejo 32.520 Badajoz  Extremadura ");
		   ciudades.push("Olot 31.246 Gerona  Cataluña ");
		   ciudades.push("Aranda de Duero 31.545 Burgos  Castilla y León  ");
		   ciudades.push("Águilas 31.450 Murcia  ");
		   ciudades.push("Burriana 32.349 Castellón  ");
		   ciudades.push("Sant Joan Despí 31.485 Barcelona  Cataluña  ");
		   ciudades.push("Vall de Uxó 31.065 Castellón  Comunidad Valenciana ");
		   ciudades.push("Puerto de la Cruz 30.585 S. C. de Tenerife  Canarias ");
		   ciudades.push("Alhaurín de la Torre 30.281 Málaga  Andalucía ");
		   ciudades.push("Oleiros 31.264 La Coruña  Galicia ");
		   ciudades.push("El Vendrell 30.225 Tarragona  Cataluña  ");
		   ciudades.push("Hellín 30.024 Albacete  Castilla-La Mancha ");
		   ciudades.push("Camargo 30.024 Cantabria    ");
		   ciudades.push("Arcos de la Frontera 29.905 Cádiz  Andalucía ");
		   ciudades.push("Lluchmayor 29.891 Islas Baleares  Islas Baleares ");
		   ciudades.push("Manises 29.717 Valencia  Comunidad Valenciana ");
		   ciudades.push("Redondela 29.863 Pontevedra  Galicia ");
		   ciudades.push("Carballo 29.689 La Coruña  Galicia ");
		   ciudades.push("Galapagar 28.934 Madrid  Comunidad de Madrid ");
		   ciudades.push("Mazarrón 28.889 Murcia    ");
		   ciudades.push("Alcázar de San Juan 29.625 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Puente Genil 28.639 Córdoba    ");
		   ciudades.push("Barberá del Vallés 28.633 Barcelona  Cataluña  ");
		   ciudades.push("Castro-Urdiales 29.000 Cantabria    ");
		   ciudades.push("Morón de la Frontera 28.295 Sevilla  Andalucía ");
		   ciudades.push("Marrachí 28.237 Islas Baleares  Islas Baleares ");
		   ciudades.push("Premiá de Mar 27.860 Barcelona  Cataluña  ");
		   ciudades.push("San Andrés del Rabanedo 27.850 León  Castilla y León  ");
		   ciudades.push("Totana 27.714 Murcia    ");
		   ciudades.push("Mahón 27.669 Islas Baleares  Islas Baleares ");
		   ciudades.push("Valdepeñas 27.634 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Ribeira 27.623 La Coruña  Galicia ");
		   ciudades.push("Torre Pacheco 27.400 Murcia    ");
		   ciudades.push("Rota 27.270 Cádiz  Andalucía ");
		   ciudades.push("Carmona 27.221 Sevilla  Andalucía ");
		   ciudades.push("San Vicente dels Horts 27.019 Barcelona  Cataluña  ");
		   ciudades.push("Ciudadela 26.972 Islas Baleares  Islas Baleares ");
		   ciudades.push("Sant Pere de Ribes 26.859 Barcelona  Cataluña  ");
		   ciudades.push("Arteijo 26.739 La Coruña  Galicia ");
		   ciudades.push("Santa Eulalia del Río 26.724 Islas Baleares  Islas Baleares ");
		   ciudades.push("San Roque 26.569 Cádiz  Andalucía ");
		   ciudades.push("Inca 26.504 Islas Baleares  Islas Baleares ");
		   ciudades.push("Coria del Río 26.499 Sevilla  Andalucía ");
		   ciudades.push("San Javier 26.337 Murcia    ");
		   ciudades.push("Martorell 26.170 Barcelona  Cataluña  ");
		   ciudades.push("Marín 26.103 Pontevedra  Galicia. ");
		   ciudades.push("Villaviciosa de Odón 26.076 Madrid  Comunidad de Madrid ");
		   ciudades.push("Azuqueca de Henares 26.064 Guadalajara  Castilla-La Mancha ");
		   ciudades.push("Camas 25.706 Sevilla  Andalucía ");
		   ciudades.push("Culleredo 25.650 La Coruña  Galicia ");
		   ciudades.push("Sitges 25.642 Barcelona  Cataluña  ");
		   ciudades.push("Pineda de Mar 25.504 Barcelona  Cataluña  ");
		   ciudades.push("Villarrobledo 25.485 Albacete  Castilla-La Mancha ");
		   ciudades.push("San Andrés de la Barca 25.383 Barcelona  Cataluña  ");
		   ciudades.push("Benicarló 25.244 Castellón    ");
		   ciudades.push("Vinaroz 25.232 Castellón    ");
		   ciudades.push("Lebrija 25.165 Sevilla  Andalucía ");
		   ciudades.push("Almansa 25.075 Albacete  Castilla-La Mancha ");
		   ciudades.push("Almuñécar 24.713 Granada  Andalucía ");
		   ciudades.push("Villanueva de la Serena 24.713 Badajoz    ");
		   ciudades.push("Caravaca de la Cruz 24.664 Murcia    ");
		   ciudades.push("Níjar 24.435 Almería    ");
		   ciudades.push("Icod de los Vinos 24.290 S. C. de Tenerife    ");
		   ciudades.push("Jumilla 24.188 Murcia    ");
		   ciudades.push("Martos 24.061 Jaén  Andalucía ");
		   ciudades.push("Catarroja 23.895 Valencia  Comunidad Valenciana ");
		   ciudades.push("Montilla 23.574 Córdoba    ");
		   ciudades.push("Molins de Rey 23.374 Barcelona  Cataluña  ");
		   ciudades.push("Ames 23.219 La Coruña  Galicia ");
		   ciudades.push("Adra 23.195 Almería    ");
		   ciudades.push("Calahorra 23.171 La Rioja    ");
		   ciudades.push("Priego de Córdoba 23.087 Córdoba    ");
		   ciudades.push("Castrillón 22.932 Asturias  Asturias ");
		   ciudades.push("Barbate 22.602 Cádiz  Andalucía ");
		   ciudades.push("Tacoronte 22.384 S. C. de Tenerife    ");
		   ciudades.push("Barañáin 22.295 Navarra  Navarra ");
		   ciudades.push("Onda 22.281 Castellón  Comunidad Valenciana ");
		   ciudades.push("Baza 22.220 Granada  Andalucía ");
		   ciudades.push("Alcalá la Real 22.129 Jaén  Andalucía ");
		   ciudades.push("Cambre 22.092 La Coruña  Galicia ");
		   ciudades.push("El Masnou 21.833 Barcelona  Cataluña  ");
		   ciudades.push("Olesa de Montserrat 21.714 Barcelona  Cataluña  ");
		   ciudades.push("Santa Perpetua de Moguda 21.644 Barcelona  Cataluña  ");
		   ciudades.push("Castellar del Vallés 21.335 Barcelona   Cataluña   ");
		   ciudades.push("Alboraya 21.263 Valencia  Comunidad Valenciana ");
		   ciudades.push("San Pedro del Pinatar 21.234 Murcia  Región de Murcia ");
		   ciudades.push("Alhaurín el Grande 21.070 Málaga  Andalucía ");
		   ciudades.push("Mejorada del Campo 21.052 Madrid  Comunidad de Madrid ");
		   ciudades.push("Laguna de Duero 21.018 Valladolid  Castilla y León  ");
		   ciudades.push("Cabra 20.935 Córdoba    ");
		   ciudades.push("Loja 20.888 Granada  Andalucía ");
		   ciudades.push("Los Barrios 20.871 Cádiz  Andalucía ");
		   ciudades.push("Tomares 20.705 Sevilla  Andalucía ");
		   ciudades.push("Medina del Campo 20.683 Valladolid  Castilla y León  ");
		   ciudades.push("Palma del Río 20.640 Córdoba    ");
		   ciudades.push("Candelaria 20.628 S. C. de Tenerife    ");
		   ciudades.push("Coín 20.551 Málaga  Andalucía ");
		   ciudades.push("Baena 20.507 Córdoba    ");
		   ciudades.push("Alfafar 20.377 Valencia  Comunidad Valenciana ");
		   ciudades.push("Nerja 20.361 Málaga  Andalucía ");
		   ciudades.push("Calatayud 20.263 Zaragoza  Aragón  ");
		   ciudades.push("Vícar 20.220 Almería    ");
		   ciudades.push("Amposta 20.159 Tarragona  Cataluña  ");
		   ciudades.push("Guadix 20.136 Granada  Andalucía ");
		   ciudades.push("San Juan de Aznalfarache 18.861 Sevilla  Andalucía ");
		   ciudades.push("Conil de la Frontera 19.890 Cádiz  Andalucía ");
		   ciudades.push("Los Llanos de Aridane 19.878 S. C. de Tenerife    ");
		   ciudades.push("Torrelodones 19.843 Madrid  Comunidad de Madrid ");
		   ciudades.push("Almazora 19.688 Castellón  Comunidad Valenciana ");
		   ciudades.push("Armilla 19.667 Granada  Andalucía ");
		   ciudades.push("S. Martín del R. Aurelio 19.436 Asturias  Asturias ");
		   ciudades.push("Monforte de Lemos 19.412 Lugo  Galicia ");
		   ciudades.push("Maracena 19.388 Granada  Andalucía ");
		   ciudades.push("Marchena 19.089 Sevilla  Andalucía ");
		   ciudades.push("Lora del Río 19.077 Sevilla  Andalucía ");
		   ciudades.push("Arahal 18.861 Sevilla  Andalucía ");
		   ciudades.push("Las Torres de Cotillas 18.842 Murcia  Región de Murcia ");
		   ciudades.push("Alhama de Murcia 18.779 Murcia  Región de Murcia ");
		   ciudades.push("Ciempozuelos 18.764 Madrid  Comunidad de Madrid ");
		   ciudades.push("Guía de Isora 18.722 S. C. de Tenerife    ");
		   ciudades.push("Mairena del Alcor 18.710 Sevilla  Andalucía ");
		   ciudades.push("Benavente 18.675 Zamora  Castilla y León  ");
		   ciudades.push("Llodio 18.633 Álava    ");
		   ciudades.push("Boiro 18.554 La Coruña  Galicia ");
		   ciudades.push("Manzanares 18.525 Ciudad Real    ");
		   ciudades.push("San José 18.382 Islas Baleares  Islas Baleares ");
		   ciudades.push("San Antonio Abad 18.366 Islas Baleares  Islas Baleares ");
		   ciudades.push("Burlada 18.316 Navarra  Navarra ");
		   ciudades.push("Algete 18.176 Madrid  Comunidad de Madrid ");
		   ciudades.push("Chipiona 17.952 Cádiz  Andalucía ");
		   ciudades.push("Santa Cruz de La Palma 17.788 S. C. de Tenerife    ");
		   ciudades.push("Navalcarnero 17.567 Madrid  Comunidad de Madrid ");
		   ciudades.push("Daimiel 17.721 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Osuna 17.594 Sevilla  Andalucía ");
		   ciudades.push("El Viso del Alcor 17.497 Sevilla  Andalucía ");
		   ciudades.push("Tarifa 17.478 Cádiz  Andalucía ");
		   ciudades.push("Pozoblanco 17.219 Córdoba    ");
		   ciudades.push("Ubrique 17.205 Cádiz  Andalucía ");
		   ciudades.push("Teo 17.168 La Coruña  Galicia ");
		   ciudades.push("Navalmoral de la Mata 17.145 Cáceres    ");
		   ciudades.push("Ejea de los Caballeros 16.941 Zaragoza  Aragón  ");
		   ciudades.push("Castilleja de la Cuesta 16.878 Sevilla  Andalucía ");
		   ciudades.push("Archena 16.707 Murcia  Región de Murcia ");
		   ciudades.push("Piélagos 16.578 Cantabria    ");
		   ciudades.push("Felanitx 16.566 Islas Baleares    ");
		   ciudades.push("Güímar 16.489 S. C. de Tenerife    ");
		   ciudades.push("La Zubia 16.450 Granada  Andalucía ");
		   ciudades.push("Zafra 16.274 Badajoz    ");
		   ciudades.push("Murcia 16.283 Murcia  Región de Murcia ");
		   ciudades.push("Benicassim 16.200 Castellón    ");
		   ciudades.push("Huércal-Overa 16.170 Almería    ");
		   ciudades.push("Las Cabezas de San Juan 16.139 Sevilla  Andalucía ");
		   ciudades.push("La Unión 16.082 Murcia  Región de Murcia ");
		   ciudades.push("Sant Celoni 16.056 Barcelona  Cataluña  ");
		   ciudades.push("Baeza 16.056 Jaén  Andalucía ");
		   ciudades.push("El Rosario 16.024 S. C. de Tenerife    ");
		   ciudades.push("S. Lorenzo de El Escorial 16.005 Madrid  Comunidad de Madrid ");
		   ciudades.push("Alcudia 15.987 Islas Baleares  Islas Baleares ");
		   ciudades.push("Pollensa 15.987 Islas Baleares  Islas Baleares ");
		   ciudades.push("Albolote 15.978 Granada  Andalucía ");
		   ciudades.push("Illescas 15.830 Toledo  Castilla-La Mancha ");
		   ciudades.push("Monzón 15.806 Huesca  Aragón  ");
		   ciudades.push("Barbastro 15.778 Huesca  Aragón  ");
		   ciudades.push("Corvera de Asturias 15.787 Asturias  Asturias ");
		   ciudades.push("Balaguer 15.769 Lérida  Cataluña  ");
		   ciudades.push("La Solana 15.761 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Bormujos 15.741 Sevilla  Andalucía ");
		   ciudades.push("San Martín de la Vega 15.677 Madrid  Comunidad de Madrid ");
		   ciudades.push("Montijo 15.648 Badajoz    ");
		   ciudades.push("El Astillero 15.635 Cantabria    ");
		   ciudades.push("Humanes de Madrid 15.589 Madrid  Comunidad de Madrid ");
		   ciudades.push("Cehegín 15.553 Murcia  Región de Murcia ");
		   ciudades.push("Vivero 15.455 Lugo  Galicia ");
		   ciudades.push("Villalba 15.455 Lugo  Galicia ");
		   ciudades.push("Cangas de Narcea 15.437 Asturias  Asturias ");
		   ciudades.push("San Justo Desvern 15.327 Barcelona  Cataluña ");
		   ciudades.push("La Roda 15.288 Albacete  Castilla-La Mancha ");
		   ciudades.push("Tárrega 15.155 Lérida  Cataluña  ");
		   ciudades.push("Alcañiz 15.130 Teruel  Aragón  ");
		   ciudades.push("Béjar 14.948 Salamanca    ");
		   ciudades.push("Torrox 14.925 Málaga  Andalucía ");
		   ciudades.push("Villanueva de la Cañada 14.809 Madrid  Comunidad de Madrid ");
		   ciudades.push("Noya 14.702 La Coruña  Galicia ");
		   ciudades.push("Santa Fe 14.599 Granada  Andalucía ");
		   ciudades.push("Berja 14.450 Almería    ");
		   ciudades.push("Villaviciosa 14.457 Asturias  Asturias ");
		   ciudades.push("Laviana 14.373 Asturias  Asturias ");
		   ciudades.push("Fene 14.346 La Coruña  Galicia ");
		   ciudades.push("Fuente Álamo de M. 14.261 Murcia  Región de Murcia ");
		   ciudades.push("Arnedo 14.245 La Rioja    ");
		   ciudades.push("Badia del Vallés 14.123 Barcelona  Cataluña   ");
		   ciudades.push("El Escorial 14.113 Madrid  Comunidad de Madrid ");
		   ciudades.push("Valdés 14.038 Asturias  Asturias ");
		   ciudades.push("Utebo 14.037 Zaragoza  Aragón  ");
		   ciudades.push("Ciudad Rodrigo 14.035 Salamanca  Castilla y León  ");
		   ciudades.push("Benetúser 13.940 Valencia  Comunidad Valenciana ");
		   ciudades.push("Santomera 13.919 Murcia  Región de Murcia ");
		   ciudades.push("Campo de Criptana 13.892 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Villaquilambre 13.891 León  Castilla y León  ");
		   ciudades.push("Barco de Valdeorras 13.800 Orense  Galicia ");
		   ciudades.push("La Algaba 13.764 Sevilla  Andalucía ");
		   ciudades.push("Verín 13.716 Orense  Galicia ");
		   ciudades.push("Carballino 13.716 Orense  Galicia ");
		   ciudades.push("Estella 13.708 Navarra  Navarra ");
		   ciudades.push("Aguilar de la Frontera 13.657 Córdoba    ");
		   ciudades.push("Santa Marta de Tormes 13.602 Salamanca  Castilla y León  ");
		   ciudades.push("Pinos Puente 13.450 Granada  Andalucía ");
		   ciudades.push("Tarancón 13.447 Cuenca  Castilla-La Mancha ");
		   ciudades.push("Atarfe 13.431 Granada  Andalucía ");
		   ciudades.push("Aller 13.421 Asturias  Asturias ");
		   ciudades.push("Los Alcázares 13.355 Murcia  Región de Murcia ");
		   ciudades.push("Sarria 13.352 Lugo  Galicia ");
		   ciudades.push("Las Gabias 13.345 Granada  Andalucía ");
		   ciudades.push("Fraga 13.284 Huesca  Aragón  ");
		   ciudades.push("Llanera 13.283 Asturias  Asturias ");
		   ciudades.push("Llanes 13.271 Asturias  Asturias ");
		   ciudades.push("Álora 13.252 Málaga  Andalucía ");
		   ciudades.push("Betanzos 13.165 La Coruña  Galicia ");
		   ciudades.push("Sada 13.134 La Coruña  Galicia ");
		   ciudades.push("Laredo 13.115 Cantabria    ");
		   ciudades.push("Lena 13.109 Asturias  Asturias ");
		   ciudades.push("Zizur Mayor 13.052 Navarra  Navarra ");
		   ciudades.push("Guadarrama 13.025 Madrid  Comunidad de Madrid ");
		   ciudades.push("Coria 12.947 Cáceres    ");
		   ciudades.push("Abarán 12.919 Murcia  Región de Murcia ");
		   ciudades.push("Villafranca de los B. 12.894 Badajoz    ");
		   ciudades.push("Puerto Lumbreras 12.881 Murcia  Región de Murcia ");
		   ciudades.push("Villanueva del Pardillo 12.879 Madrid  Comunidad de Madrid ");
		   ciudades.push("Socuéllamos 12.850 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Corbera de Llobregat 12.805 Barcelona  Cataluña  ");
		   ciudades.push("Vejer de la Frontera 12.801 Cádiz  Andalucía ");
		   ciudades.push("Santa Úrsula 12.632 S. C. de Tenerife    ");
		   ciudades.push("Mollerusa 12.569 Lérida  Cataluña  ");
		   ciudades.push("Jaca 12.553 Huesca  Aragón  ");
		   ciudades.push("Seo de Urgel 12.533 Lérida  Cataluña  ");
		   ciudades.push("Sóller 12.521 Islas Baleares  Islas Baleares ");
		   ciudades.push("Nules 12.418 Castellón  Comunidad Valenciana ");
		   ciudades.push("Gines 12.338 Sevilla  Andalucía ");
		   ciudades.push("Sama de Langreo 12.300 Asturias    ");
		   ciudades.push("Estepa 12.296 Sevilla  Andalucía ");
		   ciudades.push("Órdenes 12.294 La Coruña  Galicia ");
		   ciudades.push("Villamartín 12.291 Cádiz  Andalucía ");
		   ciudades.push("Astorga 12.285 León  Castilla y León  ");
		   ciudades.push("Pilas 12.171 Sevilla  Andalucía ");
		   ciudades.push("Bolaños de C. 12.071 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Salobreña 12.063 Granada  Andalucía ");
		   ciudades.push("Peñarroya-Pueblonuevo 12.050 Córdoba    ");
		   ciudades.push("Ogíjares 12.040 Granada  Andalucía ");
		   ciudades.push("Sanlúcar la Mayor 11.945 Sevilla  Andalucía ");
		   ciudades.push("La Carlota 11.906 Córdoba    ");
		   ciudades.push("Bullas 11.852 Murcia  Región de Murcia ");
		   ciudades.push("Brenes 11.820 Sevilla  Andalucía ");
		   ciudades.push("Huércal de Almería 11.816 Almería    ");
		   ciudades.push("Tineo 11.801 Asturias  Asturias ");
		   ciudades.push("La Puebla 11.767 Islas Baleares  Islas Baleares ");
		   ciudades.push("San Miguel de Abona 11.737 S. C. de Tenerife    ");
		   ciudades.push("Miguelturra 11.737 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Pola de Siero 11.721 Asturias    ");
		   ciudades.push("Los Puentes de G. R. 11.697 La Coruña  Galicia ");
		   ciudades.push("Torrijos 11.607 Toledo  Castilla-La Mancha ");
		   ciudades.push("Santoña 11.592 Cantabria  Cantabria ");
		   ciudades.push("Alpedrete 11.588 Madrid  Comunidad de Madrid ");
		   ciudades.push("La Puebla del Río 11.570 Sevilla  Andalucía ");
		   ciudades.push("Villablino 11.544 León  Castilla y León  ");
		   ciudades.push("Cuevas de Almanzora 11.422 Almería    ");
		   ciudades.push("Olivenza 11.389 Badajoz    ");
		   ciudades.push("Lugones 11.371 Asturias    ");
		   ciudades.push("Castellbisbal 11.272 Barcelona  Cataluña  ");
		   ciudades.push("Albox 11.271 Almería    ");
		   ciudades.push("Rianxo 11.246 La Coruña  Galicia ");
		   ciudades.push("Santiago del Teide 11.212 S. C. de Tenerife    ");
		   ciudades.push("Manilva 11.181 Málaga  Andalucía ");
		   ciudades.push("Medina-Sidonia 11.166 Cádiz  Andalucía ");
		   ciudades.push("Vera 11.159 Almería    ");
		   ciudades.push("La Corredoria 11.108 Asturias    ");
		   ciudades.push("Meco 11.094 Madrid  Comunidad de Madrid ");
		   ciudades.push("Los Corrales de B. 11.091 Cantabria  Cantabria ");
		   ciudades.push("Madridejos 11.030 Toledo  Castilla-La Mancha ");
		   ciudades.push("Grado 10.997 Asturias  Asturias ");
		   ciudades.push("La Puebla de Cazalla 10.952 Sevilla  Andalucía ");
		   ciudades.push("Tafalla 10.924 Navarra  Navarra ");
		   ciudades.push("Tarazona 10.875 Zaragoza  Aragón  ");
		   ciudades.push("Seseña 10.854 Toledo  Castilla-La Mancha ");
		   ciudades.push("Carreño 10.842 Asturias  Asturias ");
		   ciudades.push("Laracha 10.803 La Coruña  Galicia ");
		   ciudades.push("Son Servera 10.766 Islas Baleares  Islas Baleares ");
		   ciudades.push("Huétor-Vega 10.743 Granada  Andalucía ");
		   ciudades.push("Gozón 10.742 Asturias  Asturias ");
		   ciudades.push("Sonseca 10.685 Toledo  Castilla-La Mancha ");
		   ciudades.push("Santañí 10.673 Islas Baleares  Islas Baleares ");
		   ciudades.push("Haro 10.647 La Rioja    ");
		   ciudades.push("Santa Comba 10.647 La Coruña  Galicia ");
		   ciudades.push("Moralzarzal 10.604 Madrid  Comunidad de Madrid ");
		   ciudades.push("La Bañeza 10.549 León  Castilla y León  ");
		   ciudades.push("Consuegra 10.538 Toledo  Castilla-La Mancha ");
		   ciudades.push("Pallejá 10.535 Barcelona  Cataluña ");
		   ciudades.push("Quintanar de la Orden 10.471 Toledo  Castilla-La Mancha ");
		   ciudades.push("Peligros 10.385 Granada  Andalucía ");
		   ciudades.push("Reinosa 10.370 Cantabria    ");
		   ciudades.push("Fuente Palmera 10.356 Córdoba    ");
		   ciudades.push("Rute 10.309 Córdoba    ");
		   ciudades.push("Illora 10.304 Granada  Andalucía ");
		   ciudades.push("Alcora 10.297 Castellón    ");
		   ciudades.push("Tegueste 10.279 S. C. de Tenerife    ");
		   ciudades.push("Talayuela 10.249 Cáceres    ");
		   ciudades.push("Villava 10.236 Navarra  Navarra ");
		   ciudades.push("Villacañas 10.208 Toledo  Castilla-La Mancha ");
		   ciudades.push("Villarrubia de los Ojos 10.125 Ciudad Real  Castilla-La Mancha ");
		   ciudades.push("Miajadas 10.107 Cáceres  ");
		   ciudades.push("Bembibre 10.092 León  Castilla y León  ");
		   ciudades.push("Beniel 10.085 Murcia  Región de Murcia ");
		   ciudades.push("Mora 10.072 Toledo  Castilla-La Mancha ");
		   ciudades.push("Muros 10.050 La Coruña  Galicia ");
		   ciudades.push("Puerto del Son 10.025 La Coruña  Galicia ");
		   ciudades.push("Santa Cruz de Bezana 10.012 Cantabria  Cantabria ");
		   ciudades.push("Puebla del Caramiñal 10.001 La Coruña  Galicia ");
           ciudades.sort();

